cluster: "sbatch -A {cluster.account} -p {cluster.partition} -n {cluster.n} --mem={cluster.mem} -t {cluster.time}"
cluster-config: "profiles/zeus/cluster.json"

shadow-prefix: "/scratch/pawsey0001/mdelapierre/smk_work"
jobs: 512

use-singularity: true
singularity-prefix: "/group/pawsey0001/mdelapierre/.smk_singularity"
singularity-args: "-B /group -B /scratch"
